# -*- coding: utf-8 -*-
"""Avances_restuarantes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-7jiaL7X1Duqogv2FrJt5XVgjq7qTI3U
"""
# %%
import time
import requests
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point
import numpy as np
from typing import List, Dict, Any
import folium
from folium.plugins import MarkerCluster

# %%
df = pd.read_csv('data/denue_inegi_72_1.csv', encoding='latin1', low_memory=False)

# %%
codigos_rest_cafe = [
    722511, 722512, 722513, 722514,
    722515, 722516, 722517, 722518, 722519
]
# %%
df_cdmx=df[df.entidad=='Ciudad de México'].reset_index()
# %%
df_cdmx.drop('index', axis=1, inplace= True)
# %%
df_cdmx = df_cdmx[df_cdmx['codigo_act'].isin(codigos_rest_cafe)].copy()
# %%
# Punto central de la CDMX
centro_cdmx = [19.4326, -99.1332]

# Crear el mapa
m = folium.Map(location=centro_cdmx, zoom_start=12)

# Usar un clúster para no saturar
marker_cluster = MarkerCluster().add_to(m)

# Agregar marcadores
for _, row in df_cdmx.iterrows():
    if pd.notnull(row['latitud']) and pd.notnull(row['longitud']):
        folium.Marker(
            location=[row['latitud'], row['longitud']],
            popup=f"{row.get('nombre', 'Sin nombre')}",
            tooltip=row.get('clase_actividad', 'Sin giro')
        ).add_to(marker_cluster)

# Mostrar en notebook
m

# %%
df_cdmx['latitud']  = pd.to_numeric(df_cdmx['latitud'], errors='coerce')
df_cdmx['longitud'] = pd.to_numeric(df_cdmx['longitud'], errors='coerce')

denue_clean = df_cdmx.dropna(subset=['latitud','longitud']).copy()
denue_clean = denue_clean.drop_duplicates(subset=['nom_estab','latitud','longitud'])

gdf_pts = gpd.GeoDataFrame(
    denue_clean,
    geometry=gpd.points_from_xy(denue_clean['longitud'], denue_clean['latitud']),
    crs="EPSG:4326"
)
competencia = gdf_pts.copy()
# %%
minx, miny, maxx, maxy = competencia.total_bounds
grid_spacing = 0.005  # ~500 m
grid_points = []
for x in np.arange(minx, maxx, grid_spacing):
    for y in np.arange(miny, maxy, grid_spacing):
        grid_points.append((x, y))

grid_df = pd.DataFrame(grid_points, columns=['lon', 'lat'])
grid_gdf = gpd.GeoDataFrame(
    grid_df, geometry=gpd.points_from_xy(grid_df['lon'], grid_df['lat']), crs="EPSG:4326"
)
# %%
from sklearn.neighbors import BallTree
# %%
# === 3. Calcular densidad de competencia ===
# Convertir a radianes para BallTree
competencia_coords = np.radians(competencia[['latitud', 'longitud']].values)
grid_coords = np.radians(grid_df[['lat', 'lon']].values)

tree = BallTree(competencia_coords, metric='haversine')
# Radio de 500m en radianes
radius = 500 / 6371000
counts = tree.query_radius(grid_coords, r=radius, count_only=True)

grid_df['competencia'] = counts

# === 4. Calcular score simple (menos competencia es mejor) ===
# Aquí no tenemos atracción, así que solo invertimos competencia
grid_df['score'] = -grid_df['competencia']

# === 5. Seleccionar top N puntos ===
top_puntos = grid_df.sort_values('score', ascending=False).head(20)
# %%
# 1. Cargar el CSV (usa latin1 porque INEGI suele venir en ese encoding)
df_ageb = pd.read_csv("data/RESAGEBURB_09CSV20.csv", encoding="latin1")

# %%
def calcular_pesos_por_zona(ruta_denue):
    """
    Carga el archivo DENUE completo y genera pesos de afinidad por tipo de restaurante según el perfil laboral.
    Retorna un DataFrame con CVEGEO y los pesos por categoría.
    """
    import pandas as pd
    import numpy as np

    df_denue = pd.read_csv(ruta_denue, encoding='latin1', low_memory=False)
    df_denue['cve_ent'] = df_denue['cve_ent'].astype(str).str.zfill(2)
    df_denue['cve_mun'] = df_denue['cve_mun'].astype(str).str.zfill(3)
    df_denue['cve_loc'] = df_denue['cve_loc'].astype(str).str.zfill(4)
    df_denue['ageb'] = df_denue['ageb'].astype(str)
    df_denue['CVEGEO'] = df_denue['cve_ent'] + df_denue['cve_mun'] + df_denue['cve_loc'] + df_denue['ageb']
    df_denue['CVEGEO'] = df_denue['CVEGEO'].astype(str)

    def clasificar_sector(codigo):
        try:
            codigo = int(str(codigo)[:3])
        except:
            return "Otros"
        if 111 <= codigo <= 115:
            return "Agropecuario"
        elif 311 <= codigo <= 339:
            return "Industrial"
        elif 411 <= codigo <= 469:
            return "Comercio"
        elif 481 <= codigo <= 499:
            return "Transporte"
        elif 511 <= codigo <= 519:
            return "Tecnología y medios"
        elif 521 <= codigo <= 529:
            return "Finanzas y seguros"
        elif 531 <= codigo <= 539:
            return "Bienes raíces"
        elif 541 <= codigo <= 561:
            return "Servicios profesionales"
        elif 611 <= codigo <= 639:
            return "Educación y salud"
        elif 711 <= codigo <= 722:
            return "Turismo y alimentos"
        elif 811 <= codigo <= 939:
            return "Servicios personales y públicos"
        else:
            return "Otros"

    df_denue['sector'] = df_denue['codigo_act'].apply(clasificar_sector)

    df_sector_zona = (
        df_denue.groupby(['CVEGEO', 'sector'])
        .size()
        .unstack(fill_value=0)
        .reset_index()
    )
    afinidades = {
        "Restaurantes a la carta": ["Finanzas y seguros", "Servicios profesionales", "Bienes raíces", "Turismo y alimentos"],
        "Comida rápida": ["Comercio", "Industrial", "Transporte", "Educación y salud", "Turismo y alimentos"],
        "Cafeterías": ["Educación y salud", "Tecnología y medios", "Servicios profesionales"],
        "Otros": ["Agropecuario", "Servicios personales y públicos", "Otros"]
    }

    for categoria, sectores_rel in afinidades.items():
        df_sector_zona[categoria] = df_sector_zona[sectores_rel].sum(axis=1) if all(
            s in df_sector_zona.columns for s in sectores_rel
        ) else 0

    categorias = list(afinidades.keys())
    df_sector_zona[categorias] = df_sector_zona[categorias].div(df_sector_zona[categorias].sum(axis=1), axis=0).fillna(0)

    return df_sector_zona[['CVEGEO'] + categorias]
# %%
# 2. Crear la clave geográfica (CVEGEO)
df_ageb['CVEGEO'] = (
    df_ageb['ï»¿ENTIDAD'].astype(str).str.zfill(2) +
    df_ageb['MUN'].astype(str).str.zfill(3) +
    df_ageb['LOC'].astype(str).str.zfill(4) +
    df_ageb['AGEB'].astype(str)
)
# %%
cols = ['POBTOT','TOTHOG','VIVTOT','VPH_INTER']
df_ageb[cols] = df_ageb[cols].apply(pd.to_numeric, errors='coerce')

# Proporción de viviendas con internet
df_ageb['prop_internet'] = df_ageb['VPH_INTER'] / df_ageb['VIVTOT']

# Crear índice atractivo
df_ageb['atractivo'] = (
    0.5 * df_ageb['POBTOT'] +
    0.3 * df_ageb['TOTHOG'] +
    0.2 * df_ageb['prop_internet'].fillna(0) * 1000
)
# %%
# Normalizar 0–1
df_ageb['atractivo_norm'] = (
    (df_ageb['atractivo'] - df_ageb['atractivo'].min()) /
    (df_ageb['atractivo'].max() - df_ageb['atractivo'].min())
)
# %%
# Asegura que las claves existan y sean str con ceros a la izquierda
df_cdmx['cve_ent'] = df_cdmx['cve_ent'].astype(str).str.zfill(2)
df_cdmx['cve_mun'] = df_cdmx['cve_mun'].astype(str).str.zfill(3)
df_cdmx['cve_loc'] = df_cdmx['cve_loc'].astype(str).str.zfill(4)
df_cdmx['ageb']    = df_cdmx['ageb'].astype(str)  # AGEB es alfanumérico (A/B/C/D o 0-9)

df_cdmx['CVEGEO'] = df_cdmx['cve_ent'] + df_cdmx['cve_mun'] + df_cdmx['cve_loc'] + df_cdmx['ageb']
# %%
comp_ageb = df_cdmx.groupby('CVEGEO', as_index=False).agg(rest_count=('id','count'))
# %%
ageb_comp = df_ageb[['CVEGEO','POBTOT','atractivo_norm']].merge(comp_ageb, on='CVEGEO', how='left')
# %%
# Restaurantes por 1 000 habitantes (competencia relativa)
ageb_comp['rest_count'] = ageb_comp['rest_count'].fillna(0)
ageb_comp['rest_x_1000hab'] = ageb_comp['rest_count'] / ageb_comp['POBTOT'].replace(0, pd.NA) * 1000
ageb_comp['rest_x_1000hab'] = ageb_comp['rest_x_1000hab'].fillna(0)

# Normalizar competencia (0–1)
mx = ageb_comp['rest_x_1000hab'].max()
mn = ageb_comp['rest_x_1000hab'].min()
ageb_comp['competencia_norm'] = (ageb_comp['rest_x_1000hab'] - mn) / (mx - mn + 1e-9)
# %%
ageb_comp
# %%
# w1 y w2 son pesos; arranca con 1 y 1, luego calibra
w1, w2 = 1.0, 1.0
ageb_comp['score_oportunidad'] = w1*ageb_comp['atractivo_norm'] - w2*ageb_comp['competencia_norm']

# Top 20 AGEBS recomendados (mayor score)
top_agebs = ageb_comp.sort_values('score_oportunidad', ascending=False).head(20)
top_cols = ['CVEGEO','POBTOT','rest_count','rest_x_1000hab','atractivo_norm','competencia_norm','score_oportunidad']
#print(top_agebs[top_cols])

# %%
ruta_denue = "data/DENUE_CDMX.csv"  # Ruta real del archivo DENUE
df_pesos_zona = calcular_pesos_por_zona(ruta_denue)
ageb_comp['CVEGEO'] = ageb_comp['CVEGEO'].astype(str).str.zfill(13)
df_pesos_zona['CVEGEO'] = df_pesos_zona['CVEGEO'].astype(str).str.zfill(13)
ageb_comp = ageb_comp.merge(df_pesos_zona, on="CVEGEO", how="left")
# %%
display(ageb_comp)


# %%
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

# Supongamos que tu DataFrame se llama denue (solo restaurantes/cafeterías)
# Asegura tipos numéricos
df_cdmx['latitud']  = pd.to_numeric(df_cdmx['latitud'], errors='coerce')
df_cdmx['longitud'] = pd.to_numeric(df_cdmx['longitud'], errors='coerce')

# Quitar filas sin coordenadas
denue_clean = df_cdmx.dropna(subset=['latitud','longitud']).copy()

# (Opcional) deduplicar por ubicación y nombre
denue_clean = denue_clean.drop_duplicates(subset=['nom_estab','latitud','longitud'])
# %%
gdf_pts = gpd.GeoDataFrame(
    denue_clean,
    geometry=gpd.points_from_xy(denue_clean['longitud'], denue_clean['latitud']),
    crs="EPSG:4326"   # WGS84, lat/lon
)
# %%
#gdf_pts.to_file("denue_cdmx.gpkg", layer="restaurantes", driver="GPKG")
#gdf_pts.to_file("denue_cdmx.geojson", driver="GeoJSON")
# %%
import numpy as np
from folium.plugins import HeatMap
# %%
dfp = gdf_pts.dropna(subset=['latitud','longitud']).copy()

# usar per_ocu como intensidad; normaliza para que no domine el mapa
if 'per_ocu' in dfp.columns:
    dfp['per_ocu'] = pd.to_numeric(dfp['per_ocu'], errors='coerce')
    # normalización robusta (cap al percentil 95 para evitar outliers)
    cap = np.nanpercentile(dfp['per_ocu'], 95) if dfp['per_ocu'].notna().any() else 1.0
    dfp['peso'] = (dfp['per_ocu'].clip(upper=cap) / cap).fillna(0.5)  # entre 0 y 1 aprox
else:
    dfp['peso'] = 1.0  # sin columna de peso, todos valen 1

heat_data_w = dfp[['latitud','longitud','peso']].values.tolist()

m = folium.Map(location=[19.4326, -99.1332], zoom_start=12, control_scale=True)

HeatMap(
    heat_data_w,
    radius=14,
    blur=18,
    max_zoom=13,
    min_opacity=0.3
).add_to(m)

# m.save("heatmap_ponderado_denue_cdmx.html")
m
# %%
# 1. Sacar coordenadas promedio por AGEB desde tus puntos
centros = (
    gdf_pts.groupby('CVEGEO', as_index=False)
           .agg(lat_mean=('latitud','mean'),
                lon_mean=('longitud','mean'))
)

# 2. Unir con tu ageb_comp
ageb_comp_geo = ageb_comp.merge(centros, on='CVEGEO', how='left')

# 3. Preparar datos para Heatmap: [lat, lon, peso]
heat_data = ageb_comp_geo[['lat_mean','lon_mean','score_oportunidad']].dropna().values.tolist()

# Normalizar los pesos para que se vean bien
import numpy as np
weights = np.array([w for _,_,w in heat_data])
mn, mx = weights.min(), weights.max()
heat_data_norm = [[lat, lon, (w-mn)/(mx-mn+1e-9)] for lat, lon, w in heat_data]

# 4. Mapa con Folium
import folium
from folium.plugins import HeatMap

m = folium.Map(location=[19.4326, -99.1332], zoom_start=12, control_scale=True)

HeatMap(
    heat_data_norm,
    radius=18,
    blur=22,
    max_zoom=13,
    min_opacity=0.3
).add_to(m)

# Opcional: mostrar top 20 como círculos verdes
for _, r in ageb_comp_geo.sort_values('score_oportunidad', ascending=False).head(20).iterrows():
    if pd.notnull(r['lat_mean']) and pd.notnull(r['lon_mean']):
        folium.CircleMarker(
            location=[r['lat_mean'], r['lon_mean']],
            radius=5,
            color='green',
            fill=True,
            fill_opacity=0.7,
            popup=f"AGEB: {r['CVEGEO']} | Score: {r['score_oportunidad']:.2f}"
        ).add_to(m)

# m.save("mapa_score_oportunidad.html")
m
# %%
import numpy as np
import pandas as pd
import folium
from folium.plugins import HeatMap

# -----------------------------
# 1) Datos de entrada:
#   - gdf_pts: GeoDataFrame con puntos (restaurantes/cafeterías), cols: latitud, longitud, CVEGEO
#   - ageb_comp: DataFrame por AGEB con columnas:
#       ['CVEGEO','POBTOT','rest_count','rest_x_1000hab','atractivo_norm','competencia_norm','score_oportunidad']
# -----------------------------

# A) Centros por AGEB para el heatmap de oportunidad
centros = (gdf_pts.groupby('CVEGEO', as_index=False)
                  .agg(lat_mean=('latitud','mean'),
                       lon_mean=('longitud','mean')))

ageb_comp_geo = ageb_comp.merge(centros, on='CVEGEO', how='left')

# Normalizar score de oportunidad (0-1) para usarlo como intensidad del heatmap
mask_ok = ageb_comp_geo[['lat_mean','lon_mean','score_oportunidad']].notna().all(axis=1)
scores = ageb_comp_geo.loc[mask_ok, 'score_oportunidad'].values
s_min, s_max = scores.min(), scores.max()
ageb_comp_geo.loc[mask_ok, 'score_norm'] = (scores - s_min) / (s_max - s_min + 1e-9)

# Lista [lat, lon, weight] para el heatmap de oportunidad
heat_oportunidad = ageb_comp_geo.loc[mask_ok, ['lat_mean','lon_mean','score_norm']].values.tolist()

# B) Heatmap de densidad de establecimientos (desde los puntos)
dfp = gdf_pts.dropna(subset=['latitud','longitud']).copy()

# Si son muchísimos puntos, muestrear para que cargue fluido (opcional)
# dfp = dfp.sample(40000, random_state=42)  # ajusta

heat_densidad = dfp[['latitud','longitud']].values.tolist()  # peso = 1 por punto

# -----------------------------
# 2) Construcción del mapa
# -----------------------------
m = folium.Map(location=[19.4326, -99.1332], zoom_start=12, control_scale=True)

# Gradientes (paletas) distintos
grad_densidad = {0.0:'#ffffcc', 0.3:'#ffeda0', 0.6:'#feb24c', 0.85:'#f03b20', 1.0:'#bd0026'}  # amarillos→rojos
grad_oportun  = {0.0:'#e0f3f8', 0.4:'#abd9e9', 0.7:'#74add1', 1.0:'#313695'}                  # azules

# Capa 1: densidad de establecimientos (puntos crudos)
HeatMap(
    heat_densidad,
    name='Densidad de establecimientos',
    radius=12,
    blur=18,
    max_zoom=13,
    min_opacity=0.25,
    gradient=grad_densidad
).add_to(m)

# Capa 2: score de oportunidad (centros por AGEB con peso normalizado)
HeatMap(
    heat_oportunidad,
    name='Score de oportunidad',
    radius=22,       # un poco mayor para “manchas” más suaves
    blur=26,
    max_zoom=13,
    min_opacity=0.25,
    gradient=grad_oportun
).add_to(m)

# Control para alternar capas
folium.LayerControl(collapsed=False).add_to(m)

# -----------------------------
# 3) (Opcional) Leyendas simples por capa
# -----------------------------
legend_html = """
<div style="
 position: fixed;
 bottom: 20px; left: 20px; z-index: 9999;
 background: white; padding: 10px 12px; border: 1px solid #999; border-radius: 6px;
 font-size: 12px; line-height: 1.2;">
<b>Leyendas</b><br>
<span style="display:inline-block;width:10px;height:10px;background:#ffffcc;border:1px solid #ccc;"></span>
→ <span style="color:#555;">Baja densidad</span>&nbsp;&nbsp;
<span style="display:inline-block;width:10px;height:10px;background:#bd0026;border:1px solid #ccc;"></span>
→ <span style="color:#555;">Alta densidad</span>
<hr style="margin:6px 0;">
<span style="display:inline-block;width:10px;height:10px;background:#e0f3f8;border:1px solid #ccc;"></span>
→ <span style="color:#555;">Bajo score</span>&nbsp;&nbsp;
<span style="display:inline-block;width:10px;height:10px;background:#313695;border:1px solid #ccc;"></span>
→ <span style="color:#555;">Alto score</span>
</div>
"""
m.get_root().html.add_child(folium.Element(legend_html))

# Guardar si quieres
# m.save("mapa_doble_heatmap.html")

m
# %%
# Definir pesos por tipo SCIAN
pesos = {
    722511: 0.3,  # restaurante a la carta
    722513: 1.0, 722514: 1.0, 722516: 1.0, 722517: 1.0, 722518: 1.0, # comida rápida
    722515: 0.8,  # cafeterías
    722519: 0.5,  # otros
}

# Asignar peso
df_cdmx['peso_tipo'] = df_cdmx['codigo_act'].map(pesos).fillna(0.5)

# Ajustar por tamaño (per_ocu)
df_cdmx['peso_tamano'] = np.log1p(pd.to_numeric(df_cdmx['per_ocu'], errors='coerce').fillna(1))

# Competencia ponderada
df_cdmx['comp_pond'] = df_cdmx['peso_tipo'] * df_cdmx['peso_tamano']

# Sumar por AGEB
comp_ageb = df_cdmx.groupby('CVEGEO', as_index=False).agg(comp_total=('comp_pond','sum'))
# Definir pesos por tipo SCIAN
pesos = {
    722511: 0.3,  # restaurante a la carta
    722513: 1.0, 722514: 1.0, 722516: 1.0, 722517: 1.0, 722518: 1.0, # comida rápida
    722515: 0.8,  # cafeterías
    722519: 0.5,  # otros
}

# Asignar peso
df_cdmx['peso_tipo'] = df_cdmx['codigo_act'].map(pesos).fillna(0.5)

# Ajustar por tamaño (per_ocu)
df_cdmx['peso_tamano'] = np.log1p(pd.to_numeric(df_cdmx['per_ocu'], errors='coerce').fillna(1))

# Competencia ponderada
df_cdmx['comp_pond'] = df_cdmx['peso_tipo'] * df_cdmx['peso_tamano']

# Sumar por AGEB
comp_ageb = df_cdmx.groupby('CVEGEO', as_index=False).agg(comp_total=('comp_pond','sum'))
# %%
# ageb_comp ya debe tener: CVEGEO, POBTOT, rest_count, rest_x_1000hab, atractivo_norm, competencia_norm, score_oportunidad
# Centros aproximados por AGEB (media de tus puntos)
centros = (
    gdf_pts.groupby('CVEGEO', as_index=False)
           .agg(lat_mean=('latitud','mean'),
                lon_mean=('longitud','mean'))
)

ageb_comp_geo = ageb_comp.merge(centros, on='CVEGEO', how='left')

# Top N AGEBS
N = 15
cols = ['CVEGEO','POBTOT','rest_count','rest_x_1000hab','atractivo_norm','competencia_norm','score_oportunidad','lat_mean','lon_mean']
top_agebs = (ageb_comp_geo
             .dropna(subset=['lat_mean','lon_mean'])
             .sort_values('score_oportunidad', ascending=False)
             .head(N)[cols]
             .reset_index(drop=True))

top_agebs
# top_agebs.to_csv("top_agebs_recomendadas.csv", index=False)
# %%
from sklearn.neighbors import BallTree

# 1) Preparar árbol de competidores
pts_comp = gdf_pts[['latitud','longitud']].dropna().values
tree = BallTree(np.radians(pts_comp), metric='haversine')

def mejor_punto(c_lat, c_lon, r_m=500, n=200):
    """
    c_lat, c_lon: centro del AGEB (aprox)
    r_m: radio de búsqueda en metros
    n: número de muestras aleatorias en el disco
    Devuelve el punto con mayor distancia al competidor más cercano y esa distancia en metros.
    """
    R = 6371000.0
    # muestreamos puntos uniformes en un círculo de radio r_m
    rs = r_m * np.sqrt(np.random.rand(n))
    thetas = 2*np.pi*np.random.rand(n)
    dlat = (rs / R) * (180/np.pi)
    dlon = (rs / (R*np.cos(np.deg2rad(c_lat)))) * (180/np.pi)

    lats = c_lat + dlat * np.sin(thetas)
    lons = c_lon + dlon * np.cos(thetas)
    cand = np.vstack([lats, lons]).T

    # distancia al vecino más cercano (en radianes -> m)
    dist_rad, _ = tree.query(np.radians(cand), k=1)
    dist_m = dist_rad[:,0] * R
    i = np.argmax(dist_m)
    return cand[i,0], cand[i,1], dist_m[i]

# 2) Aplicar a los AGEBS top
candidatos = []
for _, r in top_agebs.iterrows():
    latc, lonc = r['lat_mean'], r['lon_mean']
    lat_best, lon_best, dmin = mejor_punto(latc, lonc, r_m=600, n=300)
    candidatos.append({
        'CVEGEO': r['CVEGEO'],
        'lat_centro': latc,
        'lon_centro': lonc,
        'lat_candidato': lat_best,
        'lon_candidato': lon_best,
        'dist_comp_mas_cercano_m': float(dmin),
        'score_oportunidad': r['score_oportunidad']
    })

df_candidatos = pd.DataFrame(candidatos).sort_values('score_oportunidad', ascending=False).reset_index(drop=True)
#df_candidatos
# df_candidatos.to_csv("candidatos_restaurante.csv", index=False)
# %%
import folium
from folium.plugins import HeatMap
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output
from sklearn.neighbors import BallTree
import numpy as np

# --- Diccionario de categorías ---
categorias = {
    "Restaurantes a la carta": [722511],
    "Comida rápida": [722513, 722514, 722516, 722517, 722518],
    "Cafeterías": [722515],
    "Otros": [722519],
    "Todos": [722511, 722513, 722514, 722515, 722516, 722517, 722518, 722519]
}

# --- Widgets ---
dropdown = widgets.Dropdown(
    options=list(categorias.keys()),
    value="Todos",
    description="Categoría:",
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='300px', height='30px')
)

btn = widgets.Button(
    description="⟳",
    layout=widgets.Layout(width='40px', height='30px', display='flex', align_items='center', justify_content='center'),
    button_style='success',
    icon="refresh"
)

output = widgets.Output()

# --- Función para seleccionar un candidato ---
def mostrar_selector_candidatos():
    """Muestra un selector interactivo basado en df_candidatos."""
    global LAT_SELECCIONADA, LON_SELECCIONADA

    if "df_candidatos" not in globals() or df_candidatos.empty:
        print("No hay candidatos disponibles. Actualiza el mapa primero.")
        return

    opciones = [
        f"{row['CVEGEO']} | Score: {row['score_oportunidad']:.2f} | DistComp: {int(row['dist_comp_mas_cercano_m'])} m"
        for _, row in df_candidatos.iterrows()
    ]

    sel_candidato = widgets.Dropdown(
        options=opciones,
        description="Elegir candidato:",
        layout=widgets.Layout(width='480px')
    )

    btn_confirmar = widgets.Button(
        description="Seleccionar punto",
        button_style='info',
        layout=widgets.Layout(width='200px')
    )

    output_candidato = widgets.Output()

    def seleccionar_punto(_):
        global LAT_SELECCIONADA, LON_SELECCIONADA
        with output_candidato:
            clear_output(wait=True)
            idx = sel_candidato.index
            punto = df_candidatos.iloc[idx]
            LAT_SELECCIONADA = punto['lat_candidato']
            LON_SELECCIONADA = punto['lon_candidato']
            print(f"Seleccionaste: CVEGEO {punto['CVEGEO']}")
            print(f"Lat: {LAT_SELECCIONADA}, Lon: {LON_SELECCIONADA}")

    btn_confirmar.on_click(seleccionar_punto)
    display(widgets.VBox([sel_candidato, btn_confirmar, output_candidato]))

# --- Función para buscar el mejor punto ---
def mejor_punto(c_lat, c_lon, tree, r_m=600, n=300):
    R = 6371000.0
    rs = r_m * np.sqrt(np.random.rand(n))
    thetas = 2*np.pi*np.random.rand(n)
    dlat = (rs / R) * (180/np.pi)
    dlon = (rs / (R*np.cos(np.deg2rad(c_lat)))) * (180/np.pi)
    lats = c_lat + dlat * np.sin(thetas)
    lons = c_lon + dlon * np.cos(thetas)
    cand = np.vstack([lats, lons]).T

    dist_rad, _ = tree.query(np.radians(cand), k=1)
    dist_m = dist_rad[:,0] * R
    i = np.argmax(dist_m)
    return cand[i,0], cand[i,1], dist_m[i]

# --- Función principal para actualizar el mapa ---
def actualizar_mapa(_):
    with output:
        clear_output(wait=True)

        categoria = dropdown.value
        codigos = categorias[categoria]

        df_sel = df_cdmx[df_cdmx['codigo_act'].isin(codigos)].copy()
        df_sel = df_sel.dropna(subset=['latitud','longitud','CVEGEO'])

        if df_sel.empty:
            print(f"No hay datos para {categoria}")
            return

        df_cdmx['CVEGEO'] = df_cdmx['CVEGEO'].astype(str)
        ageb_comp['CVEGEO'] = ageb_comp['CVEGEO'].astype(str)

        comp_ageb_cat = df_sel.groupby('CVEGEO').size()
        ageb_cat = ageb_comp.copy()
        ageb_cat['rest_count'] = ageb_cat['CVEGEO'].map(comp_ageb_cat).fillna(0)

        ageb_cat['rest_x_1000hab'] = (
            ageb_cat['rest_count'] / ageb_cat['POBTOT'].replace(0, pd.NA) * 1000
        ).where(ageb_cat['POBTOT'] > 0, 0)

        pop_min, pop_max = ageb_cat['POBTOT'].min(), ageb_cat['POBTOT'].max()
        ageb_cat['atractivo_norm'] = (ageb_cat['POBTOT'] - pop_min) / (pop_max - pop_min + 1e-9)

        comp_min, comp_max = ageb_cat['rest_x_1000hab'].min(), ageb_cat['rest_x_1000hab'].max()
        ageb_cat['competencia_norm'] = (ageb_cat['rest_x_1000hab'] - comp_min) / (comp_max - comp_min + 1e-9)

        w1, w2 = 1.0, 1.0
        ageb_cat['score_oportunidad'] = (
            w1 * ageb_cat['atractivo_norm'] - w2 * ageb_cat['competencia_norm']
        )

        centros = (df_sel.groupby('CVEGEO', as_index=False)
                          .agg(lat_mean=('latitud','mean'),
                               lon_mean=('longitud','mean')))
        ageb_comp_geo_cat = ageb_cat.merge(centros, on='CVEGEO', how='left')

        scores = ageb_comp_geo_cat.query("rest_count > 0")[['lat_mean','lon_mean','score_oportunidad']].dropna().copy()
        if scores.empty:
            print("No hay AGEBS con score para esta categoría.")
            m = folium.Map(location=[19.4326, -99.1332], zoom_start=12, control_scale=True)
            folium.LayerControl(collapsed=False).add_to(m)
            display(m)
            return

        s = scores['score_oportunidad'].values
        scores['w'] = (s - s.min()) / (s.max() - s.min() + 1e-9)

        m = folium.Map(location=[19.4326, -99.1332], zoom_start=12, control_scale=True)
        HeatMap(scores[['lat_mean','lon_mean','w']].values.tolist(),
                name=f'Score de oportunidad ({categoria})',
                radius=22, blur=26, min_opacity=0.25
        ).add_to(m)

        pts_comp = df_sel[['latitud','longitud']].dropna().values
        if pts_comp.size > 0:
            tree = BallTree(np.radians(pts_comp), metric='haversine')

            top_agebs = (
                ageb_comp_geo_cat
                .dropna(subset=['lat_mean', 'lon_mean'])
                .sort_values('score_oportunidad', ascending=False)
                .head(15)
            )

            candidatos = []
            for _, r in top_agebs.iterrows():
                if pd.notnull(r['lat_mean']) and pd.notnull(r['lon_mean']):
                    lat_best, lon_best, dmin = mejor_punto(r['lat_mean'], r['lon_mean'], tree=tree)
                    candidatos.append({
                        'CVEGEO': r['CVEGEO'],
                        'lat_candidato': lat_best,
                        'lon_candidato': lon_best,
                        'dist_comp_mas_cercano_m': dmin,
                        'score_oportunidad': r['score_oportunidad']
                    })

            global df_candidatos
            df_candidatos = pd.DataFrame(candidatos)

            if not df_candidatos.empty:
                for _, row in df_candidatos.iterrows():
                    folium.CircleMarker(
                        location=[row['lat_candidato'], row['lon_candidato']],
                        radius=6,
                        color='green',
                        fill=True,
                        fill_opacity=0.8,
                        popup=(f"CVEGEO: {row['CVEGEO']}<br>"
                               f"Score: {row['score_oportunidad']:.3f}<br>"
                               f"Dist. a competidor más cercano: {int(row['dist_comp_mas_cercano_m'])} m")
                    ).add_to(m)

        folium.LayerControl(collapsed=False).add_to(m)
        display(m)

    # --- Mostrar selector de candidatos FUERA del output del mapa ---
    if 'df_candidatos' in globals() and not df_candidatos.empty:
        mostrar_selector_candidatos()

# --- Conectar botón ---
btn.on_click(actualizar_mapa)
display(widgets.HBox([dropdown, btn]), output)
with output:
    actualizar_mapa(None)
# %%
import folium
from folium.plugins import HeatMap
import pandas as pd
import ipywidgets as widgets
from IPython.display import display, clear_output
from sklearn.neighbors import BallTree
import numpy as np
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
import time

# === DICCIONARIO DE CATEGORÍAS ===
categorias = {
    "Restaurantes a la carta": [722511],
    "Comida rápida": [722513, 722514, 722516, 722517, 722518],
    "Cafeterías": [722515],
    "Otros": [722519],
    "Todos": [722511, 722513, 722514, 722515, 722516, 722517, 722518, 722519]
}

# === WIDGETS ===
dropdown = widgets.Dropdown(
    options=list(categorias.keys()),
    value="Todos",
    description="Categoría:",
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='300px', height='30px')
)

btn = widgets.Button(
    description="⟳",
    layout=widgets.Layout(width='40px', height='30px'),
    button_style='success',
    icon="refresh"
)

output = widgets.Output()

# === FUNCIONES ===

# --- Selector de candidatos ---
def mostrar_selector_candidatos():
    """Muestra un selector interactivo basado en df_candidatos."""
    global LAT_SELECCIONADA, LON_SELECCIONADA

    if "df_candidatos" not in globals() or df_candidatos.empty:
        print("No hay candidatos disponibles. Actualiza el mapa primero.")
        return

    opciones = [
        f"{row['CVEGEO']} | Score: {row['score_oportunidad']:.2f} | DistComp: {int(row['dist_comp_mas_cercano_m'])} m"
        for _, row in df_candidatos.iterrows()
    ]

    sel_candidato = widgets.Dropdown(
        options=opciones,
        description="Elegir candidato:",
        layout=widgets.Layout(width='480px')
    )

    btn_confirmar = widgets.Button(
        description="Seleccionar punto",
        button_style='info',
        layout=widgets.Layout(width='200px')
    )

    output_candidato = widgets.Output()

    def seleccionar_punto(_):
        global LAT_SELECCIONADA, LON_SELECCIONADA
        with output_candidato:
            clear_output(wait=True)
            idx = sel_candidato.index
            punto = df_candidatos.iloc[idx]
            LAT_SELECCIONADA = punto['lat_candidato']
            LON_SELECCIONADA = punto['lon_candidato']
            print(f"Seleccionaste: CVEGEO {punto['CVEGEO']}")
            print(f"Lat: {LAT_SELECCIONADA}, Lon: {LON_SELECCIONADA}")

    btn_confirmar.on_click(seleccionar_punto)
    display(widgets.VBox([sel_candidato, btn_confirmar, output_candidato]))

# --- Mejor punto usando BallTree ---
def mejor_punto(c_lat, c_lon, tree, r_m=600, n=300):
    R = 6371000.0
    rs = r_m * np.sqrt(np.random.rand(n))
    thetas = 2*np.pi*np.random.rand(n)
    dlat = (rs / R) * (180/np.pi)
    dlon = (rs / (R*np.cos(np.deg2rad(c_lat)))) * (180/np.pi)
    lats = c_lat + dlat * np.sin(thetas)
    lons = c_lon + dlon * np.cos(thetas)
    cand = np.vstack([lats, lons]).T

    dist_rad, _ = tree.query(np.radians(cand), k=1)
    dist_m = dist_rad[:,0] * R
    i = np.argmax(dist_m)
    return cand[i,0], cand[i,1], dist_m[i]

# --- Función de scraping simple ---
def scrapear_pagina(url):
    """Retorna lista de resultados de scraping (simulado)."""
    # Configuración básica de Chrome
    options = uc.ChromeOptions()
    options.headless = True
    driver = uc.Chrome(options=options)
    driver.get(url)
    time.sleep(2)  # Espera que cargue
    
    resultados = []
    try:
        elementos = driver.find_elements(By.CSS_SELECTOR, "div")  # Cambiar selector según página real
        for e in elementos[:5]:
            resultados.append(e.text)
    except Exception as ex:
        print("Error en scraping:", ex)
    driver.quit()
    return resultados

# --- Función principal para actualizar mapa ---
def actualizar_mapa(_):
    with output:
        clear_output(wait=True)

        categoria = dropdown.value
        codigos = categorias[categoria]

        # --- Filtrado de df_cdmx por categoría ---
        df_sel = df_cdmx[df_cdmx['codigo_act'].isin(codigos)].dropna(subset=['latitud','longitud','CVEGEO'])
        if df_sel.empty:
            print(f"No hay datos para {categoria}")
            return

        df_cdmx['CVEGEO'] = df_cdmx['CVEGEO'].astype(str)
        ageb_comp['CVEGEO'] = ageb_comp['CVEGEO'].astype(str)

        comp_ageb_cat = df_sel.groupby('CVEGEO').size()
        ageb_cat = ageb_comp.copy()
        ageb_cat['rest_count'] = ageb_cat['CVEGEO'].map(comp_ageb_cat).fillna(0)
        ageb_cat['rest_x_1000hab'] = (
            ageb_cat['rest_count'] / ageb_cat['POBTOT'].replace(0,pd.NA) * 1000
        ).where(ageb_cat['POBTOT']>0,0)

        # Score de oportunidad
        pop_min, pop_max = ageb_cat['POBTOT'].min(), ageb_cat['POBTOT'].max()
        comp_min, comp_max = ageb_cat['rest_x_1000hab'].min(), ageb_cat['rest_x_1000hab'].max()
        ageb_cat['atractivo_norm'] = (ageb_cat['POBTOT'] - pop_min) / (pop_max - pop_min + 1e-9)
        ageb_cat['competencia_norm'] = (ageb_cat['rest_x_1000hab'] - comp_min) / (comp_max - comp_min + 1e-9)
        w1, w2 = 1.0, 1.0
        ageb_cat['score_oportunidad'] = w1*ageb_cat['atractivo_norm'] - w2*ageb_cat['competencia_norm']

        # Centros de AGEBS
        centros = df_sel.groupby('CVEGEO', as_index=False).agg(
            lat_mean=('latitud','mean'),
            lon_mean=('longitud','mean')
        )
        ageb_comp_geo_cat = ageb_cat.merge(centros, on='CVEGEO', how='left')

        scores = ageb_comp_geo_cat.query("rest_count > 0")[['lat_mean','lon_mean','score_oportunidad']].dropna().copy()
        if scores.empty:
            print("No hay AGEBS con score para esta categoría.")
            m = folium.Map(location=[19.4326, -99.1332], zoom_start=12, control_scale=True)
            folium.LayerControl(collapsed=False).add_to(m)
            display(m)
            return

        s = scores['score_oportunidad'].values
        scores['w'] = (s - s.min()) / (s.max() - s.min() + 1e-9)

        # Mapa base
        m = folium.Map(location=[19.4326, -99.1332], zoom_start=12, control_scale=True)
        HeatMap(scores[['lat_mean','lon_mean','w']].values.tolist(),
                name=f'Score de oportunidad ({categoria})',
                radius=22, blur=26, min_opacity=0.25
        ).add_to(m)

        # BallTree y candidatos
        pts_comp = df_sel[['latitud','longitud']].dropna().values
        if pts_comp.size > 0:
            tree = BallTree(np.radians(pts_comp), metric='haversine')
            top_agebs = ageb_comp_geo_cat.dropna(subset=['lat_mean','lon_mean']).sort_values('score_oportunidad',ascending=False).head(15)
            candidatos = []
            for _, r in top_agebs.iterrows():
                if pd.notnull(r['lat_mean']) and pd.notnull(r['lon_mean']):
                    lat_best, lon_best, dmin = mejor_punto(r['lat_mean'], r['lon_mean'], tree=tree)
                    candidatos.append({
                        'CVEGEO': r['CVEGEO'],
                        'lat_candidato': lat_best,
                        'lon_candidato': lon_best,
                        'dist_comp_mas_cercano_m': dmin,
                        'score_oportunidad': r['score_oportunidad']
                    })
            global df_candidatos
            df_candidatos = pd.DataFrame(candidatos)
            if not df_candidatos.empty:
                for _, row in df_candidatos.iterrows():
                    folium.CircleMarker(
                        location=[row['lat_candidato'], row['lon_candidato']],
                        radius=6,
                        color='green',
                        fill=True,
                        fill_opacity=0.8,
                        popup=(f"CVEGEO: {row['CVEGEO']}<br>"
                               f"Score: {row['score_oportunidad']:.3f}<br>"
                               f"Dist. a competidor más cercano: {int(row['dist_comp_mas_cercano_m'])} m")
                    ).add_to(m)

        folium.LayerControl(collapsed=False).add_to(m)
        display(m)

        # --- Scraping de ejemplo ---
        urls = ["https://www.inmuebles24.com", "https://www.vivanuncios.com.mx"]
        for url in urls:
            print(f"\n🔍 Scraping {url} ...")
            res = scrapear_pagina(url)
            for r in res:
                print("-", r[:80], "..." if len(r)>80 else "")

        # Mostrar selector de candidatos
        if 'df_candidatos' in globals() and not df_candidatos.empty:
            mostrar_selector_candidatos()

# === CONECTAR BOTÓN ===
btn.on_click(actualizar_mapa)
display(widgets.HBox([dropdown, btn]), output)
with output:
    actualizar_mapa(None)

# %%
# --- Imports
import numpy as np
import pandas as pd
import folium
from folium.plugins import HeatMap
import ipywidgets as widgets
from IPython.display import display, clear_output

# =========================
# 0) CONFIG Y UTILIDADES
# =========================

# Categorías -> códigos SCIAN (ajústalas si quieres mover algún código)
CATEGORIAS = {
    "Cafeterías": [722515],
    "Restaurantes a la carta": [722511],
    "Fast-casual / comida rápida": [722512, 722513, 722514, 722516, 722517, 722518],
    "Todos (rest + café)": [722511, 722512, 722513, 722514, 722515, 722516, 722517, 722518, 722519]
}

# Asegurar tipos en df_cdmx una sola vez (idempotente)
df_cdmx['latitud']  = pd.to_numeric(df_cdmx['latitud'], errors='coerce')
df_cdmx['longitud'] = pd.to_numeric(df_cdmx['longitud'], errors='coerce')

# Construir CVEGEO en df_cdmx (si no existe todavía)
if 'CVEGEO' not in df_cdmx.columns:
    df_cdmx['cve_ent'] = df_cdmx['cve_ent'].astype(str).str.zfill(2)
    df_cdmx['cve_mun'] = df_cdmx['cve_mun'].astype(str).str.zfill(3)
    df_cdmx['cve_loc'] = df_cdmx['cve_loc'].astype(str).str.zfill(4)
    df_cdmx['ageb']    = df_cdmx['ageb'].astype(str)
    df_cdmx['CVEGEO']  = df_cdmx['cve_ent'] + df_cdmx['cve_mun'] + df_cdmx['cve_loc'] + df_cdmx['ageb']

# Cargar Censo por AGEB (POBTOT) y preparar
ageb = pd.read_csv("/content/drive/MyDrive/Jicote/RESAGEBURB_09CSV20", encoding="latin1", low_memory=False)
if 'ï»¿ENTIDAD' in ageb.columns:
    ageb = ageb.rename(columns={'ï»¿ENTIDAD':'ENTIDAD'})

if 'CVEGEO' not in ageb.columns:
    ageb['CVEGEO'] = (ageb['ENTIDAD'].astype(str).str.zfill(2) +
                      ageb['MUN'].astype(str).str.zfill(3) +
                      ageb['LOC'].astype(str).str.zfill(4) +
                      ageb['AGEB'].astype(str))

ageb['POBTOT'] = pd.to_numeric(ageb['POBTOT'], errors='coerce')

# Widgets (slicer de categoría + radio/blur del heatmap + switch de tabla)
w_categoria = widgets.Dropdown(
    options=list(CATEGORIAS.keys()),
    value="Todos (rest + café)",
    description="Categoría:",
    style={'description_width': 'initial'},
    layout=widgets.Layout(width='350px')
)

w_radius = widgets.IntSlider(
    value=20, min=6, max=40, step=1,
    description='Radio Heat:',
    style={'description_width':'initial'},
    layout=widgets.Layout(width='300px')
)

w_blur = widgets.IntSlider(
    value=24, min=6, max=40, step=1,
    description='Blur Heat:',
    style={'description_width':'initial'},
    layout=widgets.Layout(width='300px')
)

w_tabla = widgets.Checkbox(value=True, description='Mostrar TOP 20 AGEB por competencia')
ui = widgets.HBox([w_categoria, w_radius, w_blur, w_tabla])

# =========================================
# 1) FUNCIÓN PRINCIPAL DE ACTUALIZACIÓN
# =========================================
def actualizar(categoria, radius, blur, mostrar_tabla):
    clear_output(wait=True)
    display(ui)
    print("Calculando…")

    # --- 1) Filtrar por categoría (códigos SCIAN)
    codigos = CATEGORIAS[categoria]
    df_sel = df_cdmx[df_cdmx['codigo_act'].isin(codigos)].copy()

    # Quitar filas sin coords o sin CVEGEO
    df_sel = df_sel.dropna(subset=['latitud','longitud','CVEGEO'])

    # Si no hay datos, avisar
    if df_sel.empty:
        print("No hay establecimientos para la selección actual.")
        return

    # --- 2) Competencia por AGEB: conteo + población
    comp = (df_sel.groupby('CVEGEO', as_index=False)
                  .agg(establecimientos=('id','count'),
                       lat_mean=('latitud','mean'),
                       lon_mean=('longitud','mean')))

    df_comp = comp.merge(ageb[['CVEGEO','POBTOT']], on='CVEGEO', how='left')
    df_comp['POBTOT'] = df_comp['POBTOT'].fillna(0)

    # Índice de competencia: establecimientos por 1 000 habitantes
    df_comp['comp_x_1000hab'] = np.where(
        df_comp['POBTOT'] > 0,
        df_comp['establecimientos'] / df_comp['POBTOT'] * 1000,
        0.0
    )

    # Normalizar 0–1 para usar como “intensidad” del heatmap
    mn, mx = df_comp['comp_x_1000hab'].min(), df_comp['comp_x_1000hab'].max()
    df_comp['comp_norm'] = (df_comp['comp_x_1000hab'] - mn) / (mx - mn + 1e-9)

    # --- 3) Mapa Heatmap (centro aproximado por AGEB)
    heat_ageb = df_comp[['lat_mean','lon_mean','comp_norm']].dropna().values.tolist()

    m = folium.Map(location=[19.4326, -99.1332], zoom_start=12, control_scale=True)

    HeatMap(
        heat_ageb,
        name=f'Índice de competencia ({categoria})',
        radius=radius,
        blur=blur,
        max_zoom=13,
        min_opacity=0.25,
        # gradiente propio opcional; comenta si prefieres el default
        gradient={0.0:'#ffffcc', 0.3:'#ffeda0', 0.6:'#feb24c', 0.85:'#f03b20', 1.0:'#bd0026'}
    ).add_to(m)

    folium.LayerControl(collapsed=False).add_to(m)
    display(m)

    # --- 4) Tabla TOP 20 (opcional)
    if mostrar_tabla:
        cols = ['CVEGEO','POBTOT','establecimientos','comp_x_1000hab','comp_norm']
        top = (df_comp.sort_values('comp_x_1000hab', ascending=False)
                      .head(20)[cols]
                      .reset_index(drop=True))
        print("\nTOP 20 AGEB con mayor competencia (por 1,000 habitantes) —", categoria)
        display(top)

# Ligar widgets → función
out = widgets.interactive_output(
    actualizar,
    {'categoria': w_categoria, 'radius': w_radius, 'blur': w_blur, 'mostrar_tabla': w_tabla}
)

display(ui, out)